//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuantumDesk
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANALISTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANALISTA()
        {
            this.OS = new HashSet<O>();
        }
    
        public int MATRICULA_ANALISTA { get; set; }
        public string CPF { get; set; }
        public string NOME_ANALISTA { get; set; }
        public string GERENTE { get; set; }
        public Nullable<int> CARGA_HORARIA { get; set; }
        public Nullable<int> CODIGO_ESPECIALIDADE { get; set; }
        public string STATUS_ANALISTA { get; set; }
        public string ENDERECO_ANALISTA { get; set; }
        public string TELEFONE_ANALISTA { get; set; }
        public string EMAIL_ANALISTA { get; set; }
        public string SENHA_ANALISTA { get; set; }
    
        public virtual ESPECIALIDADE ESPECIALIDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<O> OS { get; set; }
    }
}
