//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuantumDesk
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHAMADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHAMADO()
        {
            this.OS = new HashSet<O>();
        }
    
        public int CODIGO_CHAMADO { get; set; }
        public Nullable<int> CODIGO_CONTRATO { get; set; }
        public Nullable<System.DateTime> DATA_ABERTURA_CHAMADO { get; set; }
        public Nullable<System.DateTime> DATA_TERMINO_CHAMADO { get; set; }
        public string STATUS_CHAMADO { get; set; }
        public string DESCRICAO_CHAMADO { get; set; }
    
        public virtual CONTRATO CONTRATO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<O> OS { get; set; }
    }
}
