//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuantumDesk
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTRATO()
        {
            this.CHAMADOS = new HashSet<CHAMADO>();
        }
    
        public int CODIGO_CONTRATO { get; set; }
        public Nullable<int> CODIGO_CLIENTE { get; set; }
        public Nullable<System.DateTime> INICIO_CONTRATO { get; set; }
        public Nullable<System.DateTime> FIM_CONTRATO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHAMADO> CHAMADOS { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
