//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuantumDesk
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CHAMADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHAMADOS()
        {
            this.OS = new HashSet<OS>();
        }

        [Display(Name = "Codigo do Chamado:")]
        public int CODIGO_CHAMADO { get; set; }

        [Display(Name = "Codigo do Contrato:")]
        public Nullable<int> CODIGO_CONTRATO { get; set; }



        [Display(Name = "Data de Abertura do Chamado:")]//C:\QuantumDesk\QuantumDesk\Controllers\
        public Nullable<System.DateTime> DATA_ABERTURA_CHAMADO { get; set; }


        [Display(Name = "Data de Termindo do Chamado:")]
        public Nullable<System.DateTime> DATA_TERMINO_CHAMADO { get; set; }

        [Display(Name = "Status do Chamado:")]
        public Nullable<int> CODIGO_STATUS_CHAMADOS { get; set; }

        [Display(Name = "Descrição:")]
        public string DESCRICAO_CHAMADO { get; set; }
    
        public virtual CONTRATOS CONTRATOS { get; set; }
        public virtual STATUS_CHAMADOS STATUS_CHAMADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OS> OS { get; set; }
    }
}
