//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuantumDesk
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTES()
        {
            this.CONTRATOS = new HashSet<CONTRATOS>();
        }
    
        public int CODIGO_CLIENTE { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public string RESPONSAVEL { get; set; }
        public Nullable<int> CODIGO_FORMA_PAGAMENTO { get; set; }
        public Nullable<int> DIA_PAGAMENTO { get; set; }
    
        public virtual FORMA_PAGAMENTO FORMA_PAGAMENTO { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRATOS> CONTRATOS { get; set; }
    }
}
