//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuantumDesk
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIOS()
        {
            this.ANALISTAS = new HashSet<ANALISTAS>();
            this.CLIENTES = new HashSet<CLIENTES>();
        }
    
        public int ID_USUARIO { get; set; }

        public string CPF_CNPJ { get; set; }
        public string NOME_RAZAOSOCIAL { get; set; }
        public Nullable<int> CODIGO_STATUS_USUARIOS { get; set; }
        public string ENDERECO { get; set; }
        public string TELEFONE { get; set; }
        public string EMAIL { get; set; }
        public string SENHA { get; set; }
        public string TIPO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANALISTAS> ANALISTAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTES> CLIENTES { get; set; }
        public virtual STATUS_USUARIOS STATUS_USUARIOS { get; set; }
    }
}
